# Reference
# https://medium.com/@miahossain8888/how-to-create-a-react-app-with-vite-571883b100ef
# https://tomisinajayi.medium.com/setting-up-a-react-app-from-scratch-with-vite-a-step-by-step-guide-8ba53e7923cf
# https://dev.to/nandhakumar/step-by-step-guide-to-dockerize-react-app-created-using-vite-2jg3
# https://stackoverflow.com/questions/70012970/running-a-vite-dev-server-inside-a-docker-container
# https://stackoverflow.com/questions/74229258/vitereactdocker-not-working-in-container
# https://github.com/vitejs/vite/discussions/14007
services:
  frontend:
    restart: always
    container_name: frontend
    volumes:
      - ./:/app
      - /app/node_modules
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - 5173:5173